apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: track
  name: track
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: track
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: track
    spec:
      containers:
        - env:
            - name: DB_SOURCE
          image: track
          name: track
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            limits:
              memory: "1073741824"
            requests:
              memory: "536870912"
      restartPolicy: Always
