// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateTrackUser(ctx context.Context, arg CreateTrackUserParams) error
	GetCounterUser(ctx context.Context, name string) (int32, error)
	UpdateUserCounter(ctx context.Context, name string) error
}

var _ Querier = (*Queries)(nil)
