// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (string, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) error
}

var _ Querier = (*Queries)(nil)
